// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/exec/{machine_id}": {
            "post": {
                "description": "Executes a command in a running VM",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "summary": "Execute a command in a VM",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Machine ID",
                        "name": "machine_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Command to execute",
                        "name": "execCmd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ExecCommand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Command Output",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/start-vm": {
            "post": {
                "description": "Starts a new Firecracker VM with the provided configuration",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Start a new Firecracker VM",
                "parameters": [
                    {
                        "description": "VM Configuration",
                        "name": "vmConfig",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.VMConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.ExecCommand": {
            "type": "object",
            "properties": {
                "cmd": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.VMConfig": {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "properties": {
                        "auto_destroy": {
                            "type": "boolean"
                        },
                        "files": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "guest_path": {
                                        "type": "string"
                                    },
                                    "raw_value": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "guest": {
                            "type": "object",
                            "properties": {
                                "cpu_kind": {
                                    "type": "string"
                                },
                                "cpus": {
                                    "type": "integer"
                                },
                                "memory_mb": {
                                    "type": "integer"
                                }
                            }
                        },
                        "image": {
                            "type": "string"
                        },
                        "init": {
                            "type": "object",
                            "properties": {
                                "exec": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Firecracker VM API",
	Description:      "API for managing and controlling Firecracker VMs",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
